### ISSUE TITLE
signal discontinuities in samplerate conversion ?

### ISSUE THREAD

**Issue by jariseon** [TomHarte/CLK#786] opened 2020-04-12 17:14 UTC
i've managed to get audio, midi and front panel working for the yamaha fb-01 machine, and so far CLK seems like a perfect fit for my use case. there's one remaining audio issue however which i've been unable to resolve. it seems to be related to SR conversion.

to debug the issue, i'm responding to SampleSource::get_samples() with a static unipolar ramp signal. if i set `speaker.set_input_rate(44100)` to match my sound card's output rate, i will get this, as expected:

<img width="1119" alt="44100Hz" src="https://user-images.githubusercontent.com/10279461/79075027-bcd48780-7cf8-11ea-8eba-4a6c13ab71c4.png">

however, if i do `speaker.set_input_rate(62500)` then the same ramp has discontinuities:

<img width="1119" alt="62500Hz" src="https://user-images.githubusercontent.com/10279461/79075041-dece0a00-7cf8-11ea-9fc7-b5a32faa8efc.png">

can you pls take a look at this [gist](https://gist.github.com/jariseon/a0af6cad2c562fb2de5939937a81d423?ts=2) to see what's going on? thanks!

**Comment by TomHarte** [comment] 2020-04-13 02:20
I couldn't see anything obvious in the source provided — your calls to update_audio and m_opp.write should be the other way around; update_audio lets the speaker know how much time has passed since the last write, but that feels tangential.

I assume Yamaha::YM2164::get_samples doesn't make any assumptions about phase?

I'll write a direct sawtooth generator and see whether I can reproduce.

As an aside: I've been working slowly on my OPL2/OPLL and am likely to optimise the pattern in which get_samples is called, to request longer stretches at a time. But, again, not directly relevant.

**Comment by jariseon** [comment] 2020-04-13 12:21
thanks tom. i flipped the update_audio and m_opp.write call order but unfortunately that did not solve the issue. this is not urgent but when you have a moment, pls find the ramp generator code below. init stage fills the ring buffer with a ramp. the buffer content remains static thereafter. read pointer provides the phase, updated only in get_samples().

```
struct AudioBuffer {
  std::array<int16_t, 256> samples;
  size_t pread = 0, pwrite = 0;
};
AudioBuffer m_audiobuf;
...

// init stage: fill with a unipolar ramp
int N = (int)m_audiobuf.samples.size();
for (int n=0; n<N; n++)
  m_audiobuf.samples[n] = 8191 * (double(n)/N);
...

void YM2151::get_samples(std::size_t number_of_samples, int16_t* target)
{
  // if (m_chip) VGM::ym2151_update_one(m_chip, nullptr, (int)number_of_samples);
	
  for (size_t n = 0; n < number_of_samples; n++) {
    target[n] = int16_t(m_audiobuf.samples[m_audiobuf.pread] << 2);
    m_audiobuf.pread = (++m_audiobuf.pread) % m_audiobuf.samples.size();
  }
}
```

hmm, the issue might then be in my host app implementation. i'll double check to make sure i'm not doing anything stupid over there.

**Comment by jariseon** [comment] 2020-04-13 12:46
> As an aside: I've been working slowly on my OPL2/OPLL and am likely to optimise the pattern in which get_samples is called, to request longer stretches at a time.

sounds great! modern MIT-licensed OPL2/OPLL implementation is also a gift to the humanity. i'd like to rewrite the OPM/OPP [c code](https://github.com/vgmrips/vgmplay/tree/master/VGMPlay/chips) i'm currently wrapping into a similar form, after you push the final.

**Comment by TomHarte** [comment] 2020-04-19 02:34
Sorry, I obviously failed earlier in the week when looking at your gist. Having sought to reproduce, I think the problem is as below.

This tells the speaker to expect an input clock rate of 62,500Hz:

    m_speaker.set_input_rate(static_cast<float>(4000000 / 64)); // 62500 Hz

But then the following counts every single cycle that the processor performs:

	m_cycles_since_audio_update += cycle.length;

... which you then provide with only a divide by 2 to the speaker:

	m_speaker.run_for(m_audio_queue, m_cycles_since_audio_update.divide_cycles(Cycles(2)));

So in net you're telling the speaker that its input clock rate is 62,500Hz and then you're clocking it at 3Mhz.

I think you probably actually want:

	m_speaker.run_for(m_audio_queue, m_cycles_since_audio_update.divide_cycles(Cycles(2)));

i.e. divide the processor clock by 96 to produce the speaker's clock, since 6Mhz / 96 = 62,500Hz.

**Comment by jariseon** [comment] 2020-04-19 18:03
ah, that makes sense. after dividing with 96 i was still seeing discontinuities, but i think i've found the cause for the issue.

i added lines to LowpassSpeaker::resample_input_buffer() and set a breakpoint inside the conditional. the breakpoint was never hit, so it seems that the sr conversion is not the root cause for the discontinuities.

```
output_buffer_[output_buffer_pointer_] = filter_->apply(input_buffer_.data());
// --> check for discontinuities
std::size_t p1 = output_buffer_pointer_;
std::size_t p0 = p1 > 0 ? p1 - 1 : output_buffer_.size() - 1;
int32_t diff = output_buffer_[p1] - output_buffer_[p0];
if ((diff > 256) && (output_buffer_[p0] > 0))
    int xx = 0;  // breakpoint here did not fire
// <--
output_buffer_pointer_++;
```

however, a breakpoint inside the conditional in CSAudioQueue.enqueueAudioBuffer() did fire:
```
// Don't enqueue more than 4 buffers ahead of now, to ensure not too much latency accrues.
if(_enqueuedBuffers > 4) {
  [_storedBuffersLock unlock]; // <-- this was hit constantly
  return;
}
```

AudioToolbox is pulling two buffers in a row, but for each such double-pull the emu is pushing 8..12 new buffers into the queue. it is like i'm running the machine in a turbo mode. maybe i'm doing a stupid thing in the main loop?
```
- (void)startHeadless
{
  __block auto lastTime = Time::nanos_now();
  m_timer = [[CSHighPrecisionTimer alloc] initWithTask:^{
	
    const auto timeNow = Time::nanos_now();
    lastTime = std::max(timeNow - Time::Nanos(10'000'000'000 / TICKS), lastTime);
    const auto duration = timeNow - lastTime;

    @synchronized(self) {
      self->host->runFor((double)duration / 1e9);  // just calls machine.timed_machine()->run_for(x)
    }
  } interval:uint64_t(1000000000) / uint64_t(TICKS)];
}
```

**Comment by TomHarte** [comment] 2020-04-27 01:35
I don't see anything obvious in there; to talk it through:

When you call `set_clock_rate` in your constructor, you tell `MachineTypes::TimedMachine` how to map from seconds to cycles. It'll post the proper number of cycles to your machine's `run_for`, and given that you supply those to the Z80 you should get the same number back over time via `perform_machine_cycle`. So they'll accumulate at that rate into `m_cycles_since_audio_update` to measure time between audio events.

(Aside, re: Cycles versus HalfCycles; the emulator was initially cycle-centric and just used plain ints, but that turned out to be insufficient precision, so the two explicit types make sure proper conversions occur)

When you call `m_speaker.set_input_rate` you indicate what clock rate the speaker should expect via its `run_for`s. The speaker will also be notified of its intended output rate by the host, and will convert between those two.

As long the speaker knows the correct input rate and output rate, it should produce the correct number of packets, querying for the source samples via `get_samples`.

So the issue I spotted before was supplying too much to the speaker's input `run_for`; assuming that's now fixed then I guess check the output rate you supplied to the speaker and maybe add some logging in your machine's `run_for` to check that you're getting sensible cycle counts as machine input?

**Closed** 2020-09-16 23:05 UTC
Labels: bug
